---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: emqx-mqtt-auth
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: emqx-mqtt-auth-secret
    template:
      engineVersion: v2
      data:
        username: "{{ .X_EMQX_MQTT_USERNAME }}"
        password: "{{ .X_EMQX_MQTT_PASSWORD }}"
  dataFrom:
    - extract:
        key: "65858eef-5374-4b35-b953-b1f10169f689"
