---
apiVersion: apps.emqx.io/v2beta1
kind: EMQX
metadata:
  name: emqx
spec:
  image: public.ecr.aws/emqx/emqx:5.8.7

  config:
    mode: "Merge"
    data: |
      authentication {
        backend = "built_in_database"
        mechanism = "password_based"
        password_hash_algorithm {
            name = "bcrypt"
        }
        user_id_type = "username"
        bootstrap_file = "/opt/init-user.json"
        bootstrap_type = "plain"
      }
      authorization {
        sources = [
          {
            type = built_in_database
            enable = true
          }
        ]

        no_match = "deny"
      }

  bootstrapAPIKeys:
    - secretRef:
        key:
          secretName: emqx-secret
          secretKey: X_EMQX_EXPORTER_APIKEY_KEY
        secret:
          secretName: emqx-secret
          secretKey: X_EMQX_EXPORTER_APIKEY_SECRET

  coreTemplate:
    metadata:
      annotations:
        reloader.stakater.com/auto: "true"
    spec:
      replicas: 1
      envFrom:
        - secretRef:
            name: emqx-secret
      extraVolumeMounts:
        - name: init-user
          mountPath: /opt/init-user.json
          subPath: init-user.json
          readOnly: true
      extraVolumes:
        - name: init-user
          secret:
            secretName: emqx-init-user-secret

  listenersServiceTemplate:
    metadata:
      annotations:
        lbipam.cilium.io/sharing-key: default
        lbipam.cilium.io/sharing-cross-namespace: "*"
        lbipam.cilium.io/ips: "184.174.36.58"
    spec:
      type: LoadBalancer

