---
creation_rules:
  - # IMPORTANT: This rule MUST be above the others
    path_regex: talos/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age12f7sep03hzmadw2gvdz3arvhcdw4pg495ed9pgv58uwzfqm0cuasg8j8rt"
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age12f7sep03hzmadw2gvdz3arvhcdw4pg495ed9pgv58uwzfqm0cuasg8j8rt"
