---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: influxdb-auth
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: influxdb-auth-secret
    template:
      engineVersion: v2
      data:
        influxdb-user: "{{ .INFLUXDB_USER }}"
        influxdb-password: "{{ .INFLUXDB_PASSWORD }}"
  dataFrom:
    - extract:
        key: "dace540d-8625-4910-b79c-b2fb00d0c665"
