---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app influxdb
spec:
  interval: 30m
  chart:
    spec:
      chart: *app
      version: 4.12.5
      sourceRef:
        kind: HelmRepository
        name: influxdata
        namespace: flux-system
      interval: 30m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    service:
      type: ClusterIP
    persistence:
      enabled: true
      storageClass: openebs-hostpath
      size: 20Gi
    setDefaultUser:
      user:
        # keys are `influxdb-user` and `influxdb-password`.
        existingSecret: influxdb-auth-secret
    initScripts:
      enabled: true
      scripts:
        init.iql: |+
          -- Create database
          CREATE DATABASE solarlog;

          -- Create retention policies
          CREATE RETENTION POLICY autogen ON solarlog DURATION INF REPLICATION 1 DEFAULT;
          CREATE RETENTION POLICY few_days ON solarlog DURATION 7d REPLICATION 1;

          -- Continuous Queries

          CREATE CONTINUOUS QUERY summarize_1d ON solarlog
          BEGIN
            SELECT difference(last("values_E-Total")) AS Pac
            INTO solarlog.autogen.solar_1d
            FROM solarlog.autogen.solar_15s
            GROUP BY time(1d), sn
          END;

          CREATE CONTINUOUS QUERY summarize_5m ON solarlog
          BEGIN
            SELECT difference(last("values_E-Total")) * 1000 * 12 AS Pac
            INTO solarlog.autogen.solar_5m
            FROM solarlog.autogen.solar_15s
            GROUP BY time(5m), sn
          END;

          CREATE CONTINUOUS QUERY summarize_electricity_1d ON solarlog
          BEGIN
            SELECT difference(last(total)) AS total
            INTO solarlog.autogen.electricity_1d
            FROM solarlog.few_days.electricity_1s
            GROUP BY time(1d)
          END;

          CREATE CONTINUOUS QUERY summarize_electricity_5m ON solarlog
          BEGIN
            SELECT difference(last(total)) * 1000 * 12 AS total
            INTO solarlog.autogen.electricity_5m
            FROM solarlog.few_days.electricity_1s
            GROUP BY time(5m)
          END;

          CREATE CONTINUOUS QUERY summarize_electricity_15s ON solarlog
          BEGIN
            SELECT mean(current) AS current,
                   mean(current_p1) AS current_p1,
                   mean(current_p2) AS current_p2,
                   mean(current_p3) AS current_p3,
                   last(total) AS total
            INTO solarlog.autogen.electricity_15s
            FROM solarlog.few_days.electricity_1s
            GROUP BY time(15s)
          END;
