---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudnative-pg
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: cloudnative-pg-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: d200700a-feab-40f1-873a-b22100f091ef
        property: POSTGRES_SUPER_USER
    - secretKey: password
      remoteRef:
        key: d200700a-feab-40f1-873a-b22100f091ef
        property: POSTGRES_SUPER_PASSWORD
