---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres16
spec:
  instances: 3
  imageName: ghcr.io/ahinko/postgres-extended:16.4.42
  primaryUpdateStrategy: unsupervised
  storage:
    size: 50Gi
    storageClass: openebs-hostpath
  enableSuperuserAccess: true
  superuserSecret:
    name: cloudnative-pg-secret
  monitoring:
    enablePodMonitor: true

  affinity:
    enablePodAntiAffinity: false

  postgresql:
    shared_preload_libraries:
      - "vectors.so"
    parameters:
      max_connections: "300"
      shared_buffers: 512MB

  # Note: previousCluster needs to be set to the name of the previous
  # cluster when recovering from an existing cnpg cluster
  bootstrap:
    initdb:
