---
alerting:
  pushover:
    title: Gatus
    application-token: $${PUSHOVER_TOKEN}
    user-key: $${PUSHOVER_USER_KEY}
    priority: 1
    default-alert:
      description: health-check failed
      send-on-resolved: true
      failure-threshold: 3
      success-threshold: 3

connectivity:
  checker:
    target: 1.1.1.1:53
    interval: 1m

metrics: true

storage:
  type: postgres
  path: $${POSTGRES_URL}
  caching: true

ui:
  title: Status | Gatus
  header: Status

web:
  port: $${CUSTOM_WEB_PORT}
