---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ext-postgres-operator
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: ext-postgres-operator-secret
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: d200700a-feab-40f1-873a-b22100f091ef
        property: POSTGRES_SUPER_USER
    - secretKey: POSTGRES_PASS
      remoteRef:
        key: d200700a-feab-40f1-873a-b22100f091ef
        property: POSTGRES_SUPER_PASSWORD
