---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ext-postgres-operator
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: ext-postgres-operator-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        POSTGRES_USER: "{{ .POSTGRES_SUPER_USER }}"
        POSTGRES_PASS: "{{ .POSTGRES_SUPER_PASSWORD }}"
  dataFrom:
    - extract:
        key: d200700a-feab-40f1-873a-b22100f091ef
