---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app influxdb
  namespace: flux-system
spec:
  targetNamespace: home-automation
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 30m
  path: "./kubernetes/apps/home-automation/solar/influxdb"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  timeout: 5m
  dependsOn:
    - name: external-secrets
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app telegraf
  namespace: flux-system
spec:
  targetNamespace: home-automation
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 30m
  path: "./kubernetes/apps/home-automation/solar/telegraf"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  timeout: 5m
  dependsOn:
    - name: external-secrets
    - name: influxdb
    - name: emqx-cluster
