---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: bitwarden-secretsmanager 
    kind: ClusterSecretStore
  data:
  - secretKey: adminUser
    remoteRef:
      key: "a6fef985-d608-4f8b-8b0c-b1d600b6a225"
  - secretKey: adminPass 
    remoteRef:
      key: "aadcffb5-5b34-4789-a4cc-b1d600b71019"
