{
 "title": "Tagesansicht",
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "price", "label": "Euro / kWh", "query": "0.30" }
  ]
 },
 "panels": [
  {
   "title": "Leistung AC",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "WR I",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" }
     ],
     "measurement": "solar_15s",
     "select": [
      [
       { "params": [ "values_Pac" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sn", "operator": "=", "value": "2001571623" }
     ]
    },
    {
     "alias": "WR II",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" }
     ],
     "measurement": "solar_15s",
     "select": [
      [
       { "params": [ "values_Pac" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sn", "operator": "=", "value": "2001583426" }
     ]
    },
    {
     "alias": "Verbrauch",
     "measurement": "electricity_15s",
     "query": "SELECT mean(\"current\") * -1 FROM \"electricity_15s\" WHERE $timeFilter GROUP BY time(15s)",
     "select": [
      [
       { "params": [ "current" ], "type": "field" },
       { "params": [ "* -1" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Letzte Leistung AC",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Verbrauch",
     "measurement": "electricity_1s",
     "select": [
      [
       { "params": [ "current" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "WR I",
     "measurement": "solar_15s",
     "select": [
      [
       { "params": [ "values_Pac" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sn", "operator": "=", "value": "2001571623" }
     ]
    },
    {
     "alias": "WR II",
     "measurement": "solar_15s",
     "select": [
      [
       { "params": [ "values_Pac" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sn", "operator": "=", "value": "2001583426" }
     ]
    }
   ]
  },
  {
   "title": "Letzte Statuswerte  (WR I)",
   "type": "table",
   "gridPos": { "h": 10, "w": 5, "x": 14, "y": 13 },
   "targets": [
    {
     "alias": "Fehler",
     "measurement": "solar_15s",
     "select": [
      [
       { "params": [ "values_Fehler" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sn", "operator": "=", "value": "2001571623" }
     ]
    },
    {
     "alias": "Status",
     "measurement": "solar_15s",
     "select": [
      [
       { "params": [ "values_Status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sn", "operator": "=", "value": "2001571623" }
     ]
    },
    {
     "alias": "Netzfrequenz AC (Hz)",
     "measurement": "solar_15s",
     "select": [
      [
       { "params": [ "values_Fac" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sn", "operator": "=", "value": "2001571623" }
     ]
    },
    {
     "alias": "Spannung AC (V)",
     "measurement": "solar_15s",
     "select": [
      [
       { "params": [ "values_Uac" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sn", "operator": "=", "value": "2001571623" }
     ]
    },
    {
     "alias": "Spannung DC (V)",
     "measurement": "solar_15s",
     "select": [
      [
       { "params": [ "values_Upv-Ist" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sn", "operator": "=", "value": "2001571623" }
     ]
    },
    {
     "alias": "Leistung DC (W)",
     "measurement": "solar_15s",
     "select": [
      [
       { "params": [ "values_PPV" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sn", "operator": "=", "value": "2001571623" }
     ]
    },
    {
     "alias": "Betriebsdauer (h)",
     "measurement": "solar_15s",
     "select": [
      [
       { "params": [ "values_h-Total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sn", "operator": "=", "value": "2001571623" }
     ]
    },
    {
     "alias": "Gesamtleistung AC (kWh)",
     "measurement": "solar_15s",
     "select": [
      [
       { "params": [ "values_E-Total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sn", "operator": "=", "value": "2001571623" }
     ]
    }
   ]
  },
  {
   "title": "Letzte Statuswerte  (WR II)",
   "type": "table",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 13 },
   "targets": [
    {
     "alias": "Fehler",
     "measurement": "solar_15s",
     "select": [
      [
       { "params": [ "values_Fehler" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sn", "operator": "=", "value": "2001583426" }
     ]
    },
    {
     "alias": "Status",
     "measurement": "solar_15s",
     "select": [
      [
       { "params": [ "values_Status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sn", "operator": "=", "value": "2001583426" }
     ]
    },
    {
     "alias": "Netzfrequenz AC (Hz)",
     "measurement": "solar_15s",
     "select": [
      [
       { "params": [ "values_Fac" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sn", "operator": "=", "value": "2001583426" }
     ]
    },
    {
     "alias": "Spannung AC (V)",
     "measurement": "solar_15s",
     "select": [
      [
       { "params": [ "values_Uac" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sn", "operator": "=", "value": "2001583426" }
     ]
    },
    {
     "alias": "Spannung DC (V)",
     "measurement": "solar_15s",
     "select": [
      [
       { "params": [ "values_Upv-Ist" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sn", "operator": "=", "value": "2001583426" }
     ]
    },
    {
     "alias": "Leistung DC (W)",
     "measurement": "solar_15s",
     "select": [
      [
       { "params": [ "values_PPV" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sn", "operator": "=", "value": "2001583426" }
     ]
    },
    {
     "alias": "Betriebsdauer (h)",
     "measurement": "solar_15s",
     "select": [
      [
       { "params": [ "values_h-Total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sn", "operator": "=", "value": "2001583426" }
     ]
    },
    {
     "alias": "Gesamtleistung AC (kWh)",
     "measurement": "solar_15s",
     "select": [
      [
       { "params": [ "values_E-Total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sn", "operator": "=", "value": "2001583426" }
     ]
    }
   ]
  },
  {
   "title": "Tagesleistung",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Verbrauch",
     "measurement": "electricity_5m",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "/ 12" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Einspeisung",
     "measurement": "solar_5m",
     "select": [
      [
       { "params": [ "Pac" ], "type": "field" },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "/ 12" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bilanz",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Verbrauch",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "electricity_5m",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "/ 12" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Einspeisung",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "solar_5m",
     "query": "SELECT cumulative_sum(sum(\"Pac\")) / 12 / 1000 FROM \"solar_5m\" WHERE $timeFilter GROUP BY time(5m) fill(0)",
     "select": [
      [
       { "params": [ "Pac" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "/ 12" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ertrag",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "solar_5m",
     "select": [
      [
       { "params": [ "Pac" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 12 / 1000 * $price" ], "type": "math" }
      ]
     ]
    }
   ]
  }
 ]
}
{
 "title": "Monatsansicht",
 "time": { "from": "now/M", "to": "now/M" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "price", "label": "Euro / kWh", "query": "0.30" }
  ]
 },
 "panels": [
  {
   "title": "Total AC",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "WR I",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "solar_5m",
     "select": [
      [
       { "params": [ "Pac" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 12" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "sn", "operator": "=", "value": "2001571623" }
     ]
    },
    {
     "alias": "WR II",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "solar_5m",
     "select": [
      [
       { "params": [ "Pac" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 12" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "sn", "operator": "=", "value": "2001583426" }
     ]
    },
    {
     "alias": "Verbrauch",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "electricity_5m",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 12" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Bewölkungsgrad",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "weather_1d",
     "select": [
      [
       { "params": [ "clouds" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bilanz",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Verbrauch",
     "measurement": "electricity_1d",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "cumulative_sum"
       }
      ]
     ]
    },
    {
     "alias": "Einspeisung",
     "measurement": "solar_1d",
     "query": "SELECT cumulative_sum(sum(\"Pac\")) / 12 / 1000 FROM \"solar_5m\" WHERE $timeFilter GROUP BY time(5m) fill(0)",
     "select": [
      [
       { "params": [ "Pac" ], "type": "field" },
       {
        "params": [],
        "type": "cumulative_sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ertrag",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "solar_5m",
     "select": [
      [
       { "params": [ "Pac" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 12 / 1000 * $price" ], "type": "math" }
      ]
     ]
    }
   ]
  }
 ]
}
{
 "title": "Jahresansicht",
 "time": { "from": "now/y", "to": "now/y" },
 "templating": {
  "list": [
   { "name": "price", "label": "Euro / kWh", "query": "0.30" }
  ]
 },
 "panels": [
  {
   "title": "Leistung AC / 14-Tage-Durchschnitt",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "WR I",
     "groupBy": [
      { "params": [ "14d" ], "type": "time" }
     ],
     "measurement": "solar_1d",
     "select": [
      [
       { "params": [ "Pac" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sn", "operator": "=", "value": "2001571623" }
     ]
    },
    {
     "alias": "WR II",
     "groupBy": [
      { "params": [ "14d" ], "type": "time" }
     ],
     "measurement": "solar_1d",
     "select": [
      [
       { "params": [ "Pac" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sn", "operator": "=", "value": "2001583426" }
     ]
    },
    {
     "alias": "Verbrauch",
     "groupBy": [
      { "params": [ "14d" ], "type": "time" }
     ],
     "measurement": "electricity_1d",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bilanz",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Verbrauch",
     "measurement": "electricity_1d",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "cumulative_sum"
       }
      ]
     ]
    },
    {
     "alias": "Einspeisung",
     "measurement": "solar_1d",
     "query": "SELECT cumulative_sum(sum(\"Pac\")) / 12 / 1000 FROM \"solar_5m\" WHERE $timeFilter GROUP BY time(5m) fill(0)",
     "select": [
      [
       { "params": [ "Pac" ], "type": "field" },
       {
        "params": [],
        "type": "cumulative_sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ertrag",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "solar_1d",
     "select": [
      [
       { "params": [ "Pac" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " * $price" ], "type": "math" }
      ]
     ]
    }
   ]
  }
 ]
}