---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app sftpgo
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  targetNamespace: solar0
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 30m
  path: "./kubernetes/apps/solar0/sftpgo/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  dependsOn:
    - name: openebs
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_PUID: "0"
      VOLSYNC_PGID: "0"
      VOLSYNC_CLAIM: home-assistant-config
      VOLSYNC_CAPACITY: 5Gi
      GATUS_SUBDOMAIN: sftpgo.solar0
