---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: emqx-exporter
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: emqx-exporter-secret
    template:
      engineVersion: v2
      data:
        config.yaml: |
          metrics:
            target: emqx-dashboard.home-automation.svc.cluster.local:18083
            api_key: "{{ .X_EMQX_EXPORTER_APIKEY_KEY }}"
            api_secret: "{{ .X_EMQX_EXPORTER_APIKEY_SECRET }}"
          probes:
            - target: emqx-listeners.home-automation.svc.cluster.local:1883
  dataFrom:
    - extract:
        key: "ca4e2800-2336-4cdd-8c42-b1f10169b27a"
