---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: strimzi
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: strimzi-kafka-operator
      version: 0.44.0
      sourceRef:
        kind: HelmRepository
        name: strimzi
        namespace: flux-system
  values:
    dashboards:
      enabled: true
