---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gatus
spec:
  target:
    name: gatus-secret
    creationPolicy: Owner
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  data:
  - secretKey: GITHUB_TOKEN
    remoteRef:
      key: "ea7a5d56-3435-4d04-8a39-b22100b54183"
