---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-token
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: github-token-secret
    template:
      engineVersion: v2
      data:
        token: "{{ .FLUX_GITHUB_TOKEN }}"
  dataFrom:
    - extract:
        key: ea7a5d56-3435-4d04-8a39-b22100b54183
