apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:M/1pM+HB/1QI4Cz8nkY7E5kWcYcGKplx6gAFkfY3vLA=,iv:qPWW0gezg7VSXP8MOEvABpd+KL81NeS+zphvT+oJ3nc=,tag:84hNncqFDNVe2nLwOfy+wA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12f7sep03hzmadw2gvdz3arvhcdw4pg495ed9pgv58uwzfqm0cuasg8j8rt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOQjJFNERCOWl2R1dFOHgv
            ZzdRUFU1MWVxNG4veDkxU1h2Zk8vaGFWNEQ4CmxQVW9Lc25tcEt4VjdWVHc4Rlcr
            WnA0c0RuVjZ2eTlTbklVemg1MHc2VzQKLS0tIFFxRGt2YUNnbjkyS1hiUW1kUlRt
            SDZBcXVqcS9aK1A2QjY3UUZoZk5XcVkKlymfFBNXDBZ3gv+Q8w8KmrS4pmFuWMFG
            M4rXMmkLSgEDl6QzWQ7YkcTyHvIxECJkrQAGL43EXprPFUY5OIwyDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-06T21:16:09Z"
    mac: ENC[AES256_GCM,data:aPhSSwX4JOPxiNGc8EHK649HXk6/Jhf0UP1A4p7r6srlsMSRhDLbNlKffJx/qfVwN04zkefc9EEVThJ6QvjBTiBPzzzW5gJ44fhl4++ttxlPUwxeC/QQMxcfLWKzVSJruCv3vLyyLUtpo9VJ09m8+9EmRigZDEn78c7wohjVBkU=,iv:+OkjmnEkGmqzmyJ76i3HNICenomEGodXAIQ2QXoHLAM=,tag:BqHflyvsbK/YorbTVFWNHw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
