---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 30m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      home-assistant:
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          securityContext:
            runAsUser: 0 # Change when starting from scratch
            runAsGroup: 568
            runAsNonRoot: false # Change when starting from scratch
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch

        containers:
          app:
            image:
              repository: ghcr.io/home-assistant/home-assistant
              tag: 2025.3.3
            env:
              SECRET_RECORDER_DB_URL:
                valueFrom:
                  secretKeyRef:
                    name: database-homeassistant-user
                    key: POSTGRES_URL

            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false

            resources:
              requests:
                cpu: 100m
                memory: 500M
              limits:
                memory: 1000M

    service:
      app:
        controller: home-assistant
        type: ClusterIP
        ports:
          http:
            port: 8123

    ingress:
      app:
        className: nginx
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
        hosts:
          - host: &host "hass.${BASE_PATH}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - secretName: hass-cherb-de-tls
            hosts:
              - *host

    persistence:
      config:
        existingClaim: "${VOLSYNC_CLAIM}"
        advancedMounts:
          home-assistant:
            app:
              - path: /config
            code-server:
              - path: /config
