apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:Hct/ksmwP97iM6h5dS8nWErmPt7eRCo7K0A7kAuEO4Y=,iv:Z+wc21HS08ypZhPGTOvmzG4Vm4YuWdW+D9qdjFMPzIo=,tag:HRbZksfhzJDY+1VqikaC0w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12f7sep03hzmadw2gvdz3arvhcdw4pg495ed9pgv58uwzfqm0cuasg8j8rt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwaW43WnM3Y0diakNUTFBh
            SDdIaVFwL1k0azk1VWlSQWc0ZlpNa3Rrd2dBClBjN2RMMUNRZEZNV3FYbVdOV0xi
            R0hHakY1ZlVaRit2c0JkNlhrWG9QOEkKLS0tIDc2NkRZMmtISHJjQUo1Zkdqa2lY
            bEkyNDBNTVY0eFdpWklETU4wajJ1b00KWLXwvCqWfcEIbEACrJWgG5vxUy0wZxVW
            Ugw+4d4rpHsWEKr/jzT5CVnJJX/oKHKfNZYn/AIiBdVclyq7hSrA8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-06T16:40:59Z"
    mac: ENC[AES256_GCM,data:5moIFXHdKAVYk9Ryz7AB6qrPdbg/uGmyuLHjSyPaeuiuhbkSQzx6DCKtWrhRy1Ae2Rp1Zu0gTZMBCjapNcSdKH0HJ3nT47qstp1ezmLvIp4aC9NSNGKAwa03//s1lrQp7MFu3nFXkgSJZKmilSYhqYB2FEFV5HzEEiby3Gf0KsU=,iv:+jW6Wgkp6afc1TRMb0AOEOu4FH7c/5O5OIMvtx048Ns=,tag:PT9/aNAE1vS1wvDI0AnC6Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
