---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

vars:
  KUBECONFORM_SCRIPT: "{{.SCRIPTS_DIR}}/kubeconform.sh"

tasks:

  apply-ks:
    desc: Apply a Flux Kustomization resource for a cluster
    summary: |-
      APP: Path to the Flux Kustomization resource from the apps base dir (required, e.g. network/echo-server)
      NS: Namespace the Flux Kustomization exists in (default: flux-system)
    cmd: >
      flux build --namespace {{.NS}} ks {{base .APP}}
      --kustomization-file {{.KUBERNETES_DIR}}/apps/{{.APP}}/ks.yaml
      --path {{.KUBERNETES_DIR}}/apps/{{.APP}}
      {{- if contains "not found" .KS }} --dry-run \{{ end }}
      | yq 'with(select(.apiVersion == "kustomize.toolkit.fluxcd.io/v1" and .kind == "Kustomization"); .metadata.namespace = "{{.NS}}")' -
      | kubectl apply --server-side --field-manager=kustomize-controller -f -
    requires:
      vars: [APP]
    vars:
      NS: '{{.NS | default "flux-system"}}'
      KS:
        sh: flux --namespace {{.NS}} get kustomizations {{base .APP}} 2>&1
    preconditions:
      - test -f {{.KUBERNETES_DIR}}/apps/{{.APP}}/ks.yaml

  delete-ks:
    desc: Delete a Flux Kustomization resource for a cluster
    summary: |-
      APP: Path to the Flux Kustomization resource from the apps base dir (required, e.g. network/echo-server)
      NS: Namespace the Flux Kustomization exists in (default: flux-system)
    cmd: >
      flux build --namespace {{.NS}} ks {{base .KS_NAME}}
      --kustomization-file {{.KUBERNETES_DIR}}/apps/{{.APP}}/ks.yaml
      --path {{.KUBERNETES_DIR}}/apps/{{.APP}}
      {{- if contains "not found" .KS }} --dry-run \{{ end }}
      | yq 'with(select(.apiVersion == "kustomize.toolkit.fluxcd.io/v1" and .kind == "Kustomization"); .metadata.namespace = "{{.NS}}")' -
      | kubectl delete -f -
    requires:
      vars: [APP, KS_NAME]
    vars:
      NS: '{{.NS | default "flux-system"}}'
      KS:
        sh: flux --namespace {{.NS}} get kustomizations {{base .APP}} 2>&1
    preconditions:
      - test -f {{.KUBERNETES_DIR}}/apps/{{.APP}}/ks.yaml

  reconcile:
    desc: Force update Flux to pull in changes from your Git repository
    cmd: flux reconcile --namespace flux-system kustomization cluster --with-source
    preconditions:
      - msg: Missing kubeconfig
        sh: test -f {{.KUBECONFIG}}

  kubeconform:
    desc: Validate Kubernetes manifests with kubeconform
    cmd: bash {{.KUBECONFORM_SCRIPT}} {{.KUBERNETES_DIR}}
    preconditions:
      - msg: Missing kubeconform script
        sh: test -f {{.KUBECONFORM_SCRIPT}}

  resources:
    desc: Gather common resources in your cluster, useful when asking for support
    cmds:
      - for: { var: RESOURCE }
        cmd: kubectl get {{.ITEM}} {{.CLI_ARGS | default "-A"}}
    vars:
      RESOURCE: >-
        nodes
        gitrepositories
        kustomizations
        helmrepositories
        helmreleases
        certificates
        certificaterequests
        ingresses
        pods
    preconditions:
      - msg: Missing kubeconfig
        sh: test -f {{.KUBECONFIG}}

  cleanup:
    desc: Cleanup completed and errored pods
    cmds:
      - kubectl delete pod --field-selector=status.phase==Succeeded --all-namespaces
      - kubectl delete pod --field-selector=status.phase==Failed --all-namespaces
