---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname grafana
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  targetNamespace: observability
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 30m
  path: "./kubernetes/apps/observability/grafana/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
