---
apiVersion: db.movetokube.com/v1alpha1
kind: Postgres
metadata:
  name: sftpgo-db
spec:
  database: sftpgo

---
apiVersion: db.movetokube.com/v1alpha1
kind: PostgresUser
metadata:
  name: sftpgo-user
spec:
  role: sftpgo
  database: sftpgo-db
  secretName: database
  privileges: OWNER
