---
# yaml-language-server: $schema=https://kubernetes-schemas.ok8.sh/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sftpgo
spec:
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: sftpgo-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        SFTPGO_HTTPD__BINDINGS__0__OIDC__CLIENT_ID: "{{ .SFTPGO_CLIENT_ID }}"
        SFTPGO_HTTPD__BINDINGS__0__OIDC__CLIENT_SECRET: "{{ .SFTPGO_CLIENT_SECRET }}"
        SFTPGO_HTTPD__BINDINGS__0__OIDC__CONFIG_URL: "https://id.solar0.cherb.de/application/o/authorize/"
        SFTPGO_HTTPD__BINDINGS__0__OIDC__REDIRECT_BASE_URL: "https://sftpgo.solar0.cherb.de/"
        SFTPGO_HTTPD__BINDINGS__0__OIDC__SCOPES: openid,profile,email,sftpgo
        SFTPGO_HTTPD__BINDINGS__0__OIDC__ROLE_FIELD: sftpgo_role
  dataFrom:
    - extract:
        key: d2181688-59c3-4dda-8628-b22f012ff56a
