---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sftpgo
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: sftpgo
      version: 0.23.0
      sourceRef:
        kind: HelmRepository
        name: skm
        namespace: flux-system
  values:
    ui:
      ingress:
        enabled: true
        className: nginx
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
        hosts:
          - host: &host "sftpgo.solar0.cherb.de"
        tls:
          - secretName: sftpgo-solar0-tls
            hosts:
              - *host
    persistence:
      # -- Enable persistent storage for the /var/lib/sftpgo directory, saving state of the default sqlite db.
      enabled: false
      config:
        existingClaim: "${VOLSYNC_CLAIM}"
