---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sftpgo
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: sftpgo
      version: 0.23.0
      sourceRef:
        kind: HelmRepository
        name: skm
        namespace: flux-system
  values:
    envVars:
      - name: SFTPGO_DATA_PROVIDER__DRIVER
        value: postgresql
      - name: SFTPGO_DATA_PROVIDER__PORT
        value: "5432"
      - name: SFTPGO_DATA_PROVIDER__HOST
        valueFrom:
          secretKeyRef:
            name: database-sftpgo-user
            key: HOST
      - name: SFTPGO_DATA_PROVIDER__USERNAME
        valueFrom:
          secretKeyRef:
            name: database-sftpgo-user
            key: LOGIN
      - name: SFTPGO_DATA_PROVIDER__PASSWORD
        valueFrom:
          secretKeyRef:
            name: database-sftpgo-user
            key: PASSWORD
      - name: SFTPGO_DATA_PROVIDER__NAME
        valueFrom:
          secretKeyRef:
            name: database-sftpgo-user
            key: DATABASE_NAME
    envFrom:
      - secretRef:
          name: sftpgo-secret
    volumeMounts:
      - name: sftpgo-storage
        mountPath: /srv/sftpgo
    volumes:
      - name: sftpgo-storage
        persistentVolumeClaim:
          claimName: sftpgo-data

    ui:
      ingress:
        enabled: true
        className: nginx
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
        hosts:
          - host: &host "sftpgo.solar0.cherb.de"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: sftpgo-solar0-tls
            hosts:
              - *host

    services:
      public:
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/sharing-key: default
          lbipam.cilium.io/sharing-cross-namespace: "*"
          lbipam.cilium.io/ips: "184.174.36.58"
        ports:
          sftp:
            port: 22
