apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bitwarden-secretsmanager
spec:
  provider:
    bitwardensecretsmanager:
      bitwardenServerSDKURL: https://bitwarden-sdk-server.security.svc.cluster.local:9998
      organizationID: 08f28702-7353-4344-bfcd-b1d600b5e1a4
      projectID: 08888910-d21b-4cff-ac15-b1d600b61320
      auth:
        secretRef:
          credentials:
            key: token
            name: bitwarden-access-token
            namespace: security
      caProvider:
        type: Secret
        name: bitwarden-tls-certs
        namespace: security
        key: ca.crt
