---
# yaml-language-server: $schema=https://kubernetes-schemas.ok8.sh/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app authentik
spec:
  interval: 30m
  chart:
    spec:
      chart: authentik
      version: 2024.12.3
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      deploymentAnnotations:
        secret.reloader.stakater.com/reload: "authentik-secret"
      storageClass: openebs-hostpath
      envFrom:
        - secretRef:
            name: authentik-secret
    authentik:
      log_level: info
      avatars: "gravatar,initials"
      error_reporting:
        enable: false
        send_pii: false
    server:
      initContainers:
        - name: init-db
          image: ghcr.io/onedr0p/postgres-init:16.8
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: authentik-secret
      metrics:
        serviceMonitor:
          enabled: true
      ingress:
        enabled: true
        className: nginx
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
        hosts:
          - &host id.solar0.cherb.de
        paths:
          - /
        tls:
          - secretName: id-solar0-tls
            hosts:
              - *host
    prometheus:
      rules:
        enabled: true
    postgresql:
      enabled: false
    redis:
      enabled: true
